### ISSUE TITLE
unable to access '/ dev / binder': No such file or directory

### ISSUE THREAD

**Issue by nikatshun** [anbox/anbox-modules#20] opened 2019-05-15 10:39 UTC
hello, trouble on the last command.
$ sudo modprobe ashmem_linux
$ sudo modprobe binder_linux
$ lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          151552  0
ashmem_linux           20480  0
$ ls -alh /dev/binder /dev/ashmem
ls: unable to access '/ dev / binder': No such file or directory
crw------- 1 root root 10, 54 мая 15 12:33 /dev/ashmem

ubuntu 19.4

**Comment by KenSharp** [comment] 2019-07-01 12:30
Are you using the anbox modules or the upstream modules?

**Comment by Hattshire** [comment] 2019-07-13 04:49
Did you installed the udev files?
udev is what makes the nodes on /dev, not the driver itself, the driver/kernel just touches /sys on module load

**Comment by leela-popos** [comment] 2019-09-15 09:50
I am using anbox madules and I already had the udev files, still I have same issue.
<pre><font color="#4E9A06"><b>leela@pop-os</b></font>:<font color="#3465A4"><b>~</b></font>$ ls -1 /dev/{ashmem,binder}
ls: cannot access &apos;/dev/binder&apos;: No such file or directory
<span style="background-color:#333333"><font color="#C4A000"><b>/dev/ashmem</b></font></span>
</pre>

**Comment by aproposnix** [comment] 2019-10-03 07:52
I get the same error. 

**$** ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/binder': No such file or directory
/dev/ashmem

I'm on Ubuntu 18.04 running the 5.0.0-29-generic kernel

**Comment by zaeima** [comment] 2019-10-29 11:19
I got the same issue. I am using KDE neon user edition, which is using the 5.0.0-32-generic kernel.

I have tried both installing the anbox-modules from the morphis/anbox-support PPA, and manually compiling and installing them from the instructions in this git repository. Both times, `ls -alh /dev/binder /dev/ashmem` and `ls -1 /dev/{ashmem,binder}` return the error `ls: cannot access '/dev/binder': No such file or directory`. 

However, when I do `lsmod | grep -e ashmem_linux -e binder_linux`, the binder_linux module shows up. But when I attempt to run the anbox application manager, it loads for a while before crashing.

**Comment by muelli** [comment] 2019-10-31 21:15
same here on a stock ubuntu 19.10, i.e. using the stock kernel.

**Comment by KBeDeveloper** [comment] 2019-11-01 01:59
Did you check the logs with <code>journalctl -xe</code>?

I've found these outputs:
```
systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove

systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove

systemd-modules-load[26813]: Failed to insert module 'ashmem_linux': Operation not permitted

systemd-modules-load[26813]: Failed to insert module 'binder_linux': Operation not permitted

systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE

systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.

systemd[1]: Failed to start Load Kernel Modules.
```

And these:

```
systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:1:

systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:2:

systemd-modules-load[26813]: Failed to insert module 'ashmem>

systemd-modules-load[26813]: Failed to insert module 'binder>

systemd[1]: systemd-modules-load.service: Main process exite>
```

I'm using Fedora 30 with Linux 5.3.7-200.fc30.x86_64

**Comment by thomasesr** [comment] 2019-11-10 21:45
I'm heaving the same issue:

```
$ sudo ls -alh /dev/binder /dev/ashmem
ls: não foi possível acessar '/dev/binder': Arquivo ou diretório inexistente
crw------- 1 root root 10, 54 nov 10 18:32 /dev/ashmem
$ /dev$ sudo lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          163840  0
ashmem_linux           20480  0

$ tail -n 80 /var/log/syslog
Nov 10 18:27:40 pop-os systemd[1]: Condition check resulted in Anbox Container Manager being skipped.
Nov 10 18:27:53 pop-os anbox: Failed to start as either binder or ashmem kernel drivers are not loaded
Nov 10 18:28:43 pop-os anbox: Application manager service is not running yet
Nov 10 18:30:42 pop-os systemd-resolved[888]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Nov 10 18:30:42 pop-os systemd-resolved[888]: message repeated 3 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.]
Nov 10 18:32:12 pop-os kernel: [ 6625.664667] ashmem_linux: module is from the staging directory, the quality is unknown, you have been warned.
Nov 10 18:32:12 pop-os kernel: [ 6625.665460] ashmem: initialized
Nov 10 18:32:39 pop-os anbox: Failed to start as either binder or ashmem kernel drivers are not loaded
Nov 10 18:33:29 pop-os anbox: Application manager service is not running yet
Nov 10 18:35:46 pop-os kernel: [ 6839.102257] EDAC amd64: Node 0: DRAM ECC disabled.
Nov 10 18:35:46 pop-os kernel: [ 6839.102259] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
Nov 10 18:35:46 pop-os kernel: [ 6839.102259]  Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
Nov 10 18:35:46 pop-os kernel: [ 6839.102259]  (Note that use of the override may cause unknown side effects.)
Nov 10 18:35:46 pop-os systemd-udevd[530]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
Nov 10 18:35:46 pop-os systemd-udevd[530]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
Nov 10 18:35:46 pop-os systemd[1]: systemd-modules-load.service: Succeeded.
Nov 10 18:35:46 pop-os systemd[1]: Stopped Load Kernel Modules.
Nov 10 18:35:46 pop-os systemd[1]: Stopping Load Kernel Modules...
Nov 10 18:35:46 pop-os systemd[1]: Starting Load Kernel Modules...
Nov 10 18:35:46 pop-os systemd[1]: Started Load Kernel Modules.
Nov 10 18:36:23 pop-os kernel: [ 6876.808101] EDAC amd64: Node 0: DRAM ECC disabled.
Nov 10 18:36:23 pop-os kernel: [ 6876.808104] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
Nov 10 18:36:23 pop-os kernel: [ 6876.808104]  Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
Nov 10 18:36:23 pop-os kernel: [ 6876.808104]  (Note that use of the override may cause unknown side effects.)
Nov 10 18:36:23 pop-os systemd-udevd[530]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
Nov 10 18:36:23 pop-os systemd-udevd[530]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
Nov 10 18:36:24 pop-os systemd[1]: systemd-modules-load.service: Succeeded.
Nov 10 18:36:24 pop-os systemd[1]: Stopped Load Kernel Modules.
Nov 10 18:36:24 pop-os systemd[1]: Stopping Load Kernel Modules...
Nov 10 18:36:24 pop-os systemd[1]: Starting Load Kernel Modules...
Nov 10 18:36:24 pop-os systemd[1]: Started Load Kernel Modules.
Nov 10 18:37:08 pop-os anbox: Failed to start as either binder or ashmem kernel drivers are not loaded
Nov 10 18:37:59 pop-os anbox: Application manager service is not running yet

```

**Comment by joaoapel** [comment] 2019-11-27 00:16
Same error here, on Ubuntu 19.10

**Comment by YashaswiNayak99** [comment] 2019-12-08 08:20
Same issue here, using PopOS 19.10

**Comment by JamesSwift** [comment] 2019-12-13 11:08
Same on PopOS 19.10

**Comment by JamesSwift** [comment] 2019-12-13 11:21
This bug report seems relevant: [https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849493](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849493)

**Comment by roydenyates** [comment] 2019-12-13 23:40
> This bug report seems relevant: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849493

I believe not - the driver is present as a module and starts to load (it shows up in lsmod) but udev (?) fails to make the /dev/binder node. There is nothing shown in dmesg (but there is for ashmem). Symptomatically, you cannot "modprobe -r binder_linux" (ashmem with /dev/ashmem created removes just fine).

**Comment by KenSharp** [comment] 2019-12-14 14:39
`systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove

systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove`

The cause has already been identified. No need to keep guessing.

**Comment by JamesSwift** [comment] 2019-12-14 16:02
Great. If the cause is known, is there a way for the users to temporarily fix it? The project seems to be pretty inactive at the moment.

**Comment by roydenyates** [comment] 2019-12-14 16:19
> ```
> systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
> 
> systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
> ```
> 
> The cause has already been identified. No need to keep guessing.

I don't get the point - the module binder_linux does not load properly to create /dev/binder. That's true without anbox installed and thus that udev rule.

**Comment by justinslatten** [comment] 2019-12-17 21:29
> ```
> systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:1: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
> 
> systemd-udevd[568]: /usr/lib/udev/rules.d/99-anbox.rules:2: NAME="%k" is ignored, because it breaks kernel supplied names; please remove
> ```
> 
> The cause has already been identified. No need to keep guessing.

This doesn't appear to be the cause of this problem. I believe this is just a warning message. I supplied static name and still running into issue with binder. 

Any idea what this is about?

Dec 17 13:23:02 localhost kernel: [279949.620827] EDAC amd64: Node 0: DRAM ECC disabled.
Dec 17 13:23:02 localhost kernel: [279949.620828] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
Dec 17 13:23:02 localhost kernel: [279949.620828]  Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
Dec 17 13:23:02 localhost kernel: [279949.620828]  (Note that use of the override may cause unknown side effects.)

**Comment by PanosChristopoulos** [comment] 2020-01-02 12:51
Have the same problem. Do we have a solution yet?

**Comment by morphis** [comment] 2020-01-02 13:17
The binder driver in Ubuntu 19.10 doesn't create /dev/binder when loaded. That is intentional. Instead it provides support for binderfs (see https://brauner.github.io/2019/01/09/android-binderfs.html) which will be used instead once https://github.com/anbox/anbox/pull/1309 is merged. Closing as not a bug.

**Closed by morphis** 2020-01-02 13:17 UTC

**Comment by auspex** [comment] 2020-01-27 15:37
How is this NOT a bug? The Anbox site tells us we don't need to install the Binder kernel module, because it's already installed. And, in fact, I couldn't _anyway_ because you didn't have sources for 19.10. So, unless there's a workaround, I can't have anbox on a 19.10 system.

**Comment by Disctanger** [comment] 2020-02-09 02:04
I have installed anbox snap and anbox modules to Fedora kernel 5.3.18-2.surface.fc31.x86_64 (currently running this kernel)

I am also having similar problem as author of this post:
> $ ls -alh /dev/binder /dev/ashmem
> ls: unable to access '/ dev / binder': No such file or directory

after reboot i am using ` $ sudo modprobe binder_linux ` to attach binder_linux

Then i am having the following result:
`
$ ls -1 /dev/{ashmem,binder}
/dev/ashmem
/dev/binder
`

If i run anbox I am seeing the following errors(?)
![image](https://user-images.githubusercontent.com/10447714/74094868-93965000-4b2b-11ea-886f-584192f20fac.png)

I am thinking my issue is also related to this post.
Would be wonderful if we could get more info about how to fix binder problem.

**Comment by swd543** [comment] 2020-04-27 14:15
Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.

**Comment by koalyorg** [comment] 2020-04-28 11:30
> Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.

Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.

**Comment by sajedulsakib001** [comment] 2020-04-30 09:45
> > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> 
> Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.
 
will it work without binder??????

**Comment by koalyorg** [comment] 2020-04-30 09:49
> > > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> > 
> > 
> > Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.
> 
> will it work without binder??????

If you are on Ubuntu 20.04 you won't need to install (and start) it, because it is installed (see https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411)

**Comment by sajedulsakib001** [comment] 2020-04-30 16:01
> > > > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> > > 
> > > 
> > > Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.
> > 
> > 
> > will it work without binder??????
> 
> If you are on Ubuntu 20.04 you won't need to install (and start) it, because it is installed (see [#20 (comment)](https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411))

but sir i am also getting the same error

sajedul@Lenovo-B40-80:~$ ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/binder': No such file or directory
/dev/ashmem
sajedul@Lenovo-B40-80:~$

**Comment by koalyorg** [comment] 2020-04-30 17:58
> > > > > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> > > > 
> > > > 
> > > > Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.
> > > 
> > > 
> > > will it work without binder??????
> > 
> > 
> > If you are on Ubuntu 20.04 you won't need to install (and start) it, because it is installed (see [#20 (comment)](https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411))
> 
> but sir i am also getting the same error
> 
> sajedul@Lenovo-B40-80:~$ ls -1 /dev/{ashmem,binder} ls: cannot access '/dev/binder': No such file or directory /dev/ashmem sajedul@Lenovo-B40-80:~$
> 
> should i run anbox install command???

It would be enough to test ashmem, because binder doesn't exists in that place anymore. Probably you would have to start ashmem, if that doesn't work you might have to disable secure boot in bios/uefi.

**Comment by shamallah** [comment] 2020-05-17 08:12
I have the same issue on Ubuntu 20.04
root@vic:~# ls -1 /dev/{ashmem,binder} /dev/ashmem /dev/binder
ls: cannot access '/dev/binder': No such file or directory
ls: cannot access '/dev/binder': No such file or directory
/dev/ashmem
/dev/ashmem


> > > > > > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> > > > > 
> > > > > 
> > > > > Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.
> > > > 
> > > > 
> > > > will it work without binder??????
> > > 
> > > 
> > > If you are on Ubuntu 20.04 you won't need to install (and start) it, because it is installed (see [#20 (comment)](https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411))
> > 
> > 
> > but sir i am also getting the same error
> > sajedul@Lenovo-B40-80:~$ ls -1 /dev/{ashmem,binder} ls: cannot access '/dev/binder': No such file or directory /dev/ashmem sajedul@Lenovo-B40-80:~$
> > should i run anbox install command???
> 
> It would be enough to test ashmem, because binder doesn't exists in that place anymore. Probably you would have to start ashmem, if that doesn't work you might have to disable secure boot in bios/uefi (note that this is not ideal, see [anbox/anbox#1070](https://github.com/anbox/anbox/issues/1070) ).

**Comment by Sproggy** [comment] 2020-06-05 21:25
i am using Xubuntu 20.04, i had the same issue with Anbox until i followed koalyorg's advice

run

sudo snap install --edge --devmode anbox

then run

sudo modprobe ashmem_linux

**Comment by thima2017** [comment] 2020-06-22 23:14
The both snap versions segfault on my system (Lubuntu 20.04)

this is what beta version shows:
```
$ snap run anbox session-manager
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
[ 2020-06-22 23:05:52] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2020-06-22 23:05:52] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2020-06-22 23:05:53] [daemon.cpp:61@Run] Container is not running
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Stack trace (most recent call last) in thread 6660:
#8    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#7    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3e9feb241c, in clone
#6    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f3ea19646b9, in 
#5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f3ea0443d37, in 
#4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f3ea0418700, in std::terminate()
#3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f3ea04186b5, in 
#2    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f3ea041a84c, in __gnu_cxx::__verbose_terminate_handler()
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3e9fde2029, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3e9fde0428, in gsignal
Aborted (Signal sent by tkill() 6474 1000)
Aborted (core dumped)
```

**Comment by ntzxtyz** [comment] 2020-07-22 10:48
The same error here on Ubuntu 20.04,

**Comment by thima2017** [comment] 2020-07-22 12:52
Bugreport on launchpad https://bugs.launchpad.net/ubuntu/+source/anbox/+bug/1884810

**Comment by ghost** [comment] 2020-08-17 19:17
> > Same issue with Ubuntu 20.04. You dont seem to support the newer versions of ubuntu so better put it in the docs.
> 
> Anbox works fine with Ubuntu 20.04. Installed it via snap (edge) and done sudo modprobe ashmem_linux.

the snap version is not installing & the repository version has a bug that is no bug and get no fix = anbox is unusable

**Comment by ondbyte** [comment] 2020-10-04 15:30
this can be resolved, take look at, [this](https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox/1590708#1590708)

**Comment by krzydoug** [comment] 2020-10-06 21:40
> 
> 
> this can be resolved, take look at, [this](https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox/1590708#1590708)

I can confirm this finally got my anbox working again, THANK YOU!

**Comment by karanpathak** [comment] 2020-11-08 20:23
> > this can be resolved, take look at, [this](https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox/1590708#1590708)
> 
> I can confirm this finally got my anbox working again, THANK YOU!

It doesn't seem to work for me!

**Comment by zachlai** [comment] 2020-12-31 07:36
I tried this way, and solved this issue.
see:
https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox

**Comment by amirji** [comment] 2021-01-20 13:32
Terrible support.

**Comment by thexcryptocompany** [comment] 2021-02-07 09:19
I'm using the latest version of pop os but the above link does'nt help me in any way do i need to install snap??? or something??? else

**Comment by kunalrustagi08** [comment] 2021-02-13 13:31
> I'm using the latest version of pop os but the above link does'nt help me in any way do i need to install snap??? or something??? else

I installed snap on pop os for installing anbox, but I am getting the error `ls: cannot access '/dev/binder': No such file or directory`.

Any luck?

**Comment by ondbyte** [comment] 2021-02-13 18:11
> > I'm using the latest version of pop os but the above link does'nt help me in any way do i need to install snap??? or something??? else
> 
> I installed snap on pop os for installing anbox, but I am getting the error `ls: cannot access '/dev/binder': No such file or directory`.
> 
> Any luck?

This thread addresses the exact problem in your question, check the answers mentioned above

**Comment by alfredousan** [comment] 2021-06-12 23:27
> I tried this way, and solved this issue.
> see:
> https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox

unfortunately that didn't work for me either way

**Comment by alfredousan** [comment] 2021-06-12 23:29
> The binder driver in Ubuntu 19.10 doesn't create /dev/binder when loaded. That is intentional. Instead it provides support for binderfs (see https://brauner.github.io/2019/01/09/android-binderfs.html) which will be used instead once [anbox/anbox#1309](https://github.com/anbox/anbox/pull/1309) is merged. Closing as not a bug.

is there a workaround to use this software without using bindings, by chance? this seems too difficult to troubleshoot! thanks for your attention :)

**Comment by Hattshire** [comment] 2021-06-13 20:21
The correcto way of doing it is by using udev, but if you would like to
drop a bash script to do it, you can have one like
```
#/bin/sh
mkdir /dev/binder
mount -t binderfs /dev/binder
```
execute it using systemd on boot, or every so with crontab and it should
work, however, it's kinda sketchy and the udev way is far more simple an
elegant.

**Comment by revdeluxe** [comment] 2021-11-22 05:07
> How is this NOT a bug? The Anbox site tells us we don't need to install the Binder kernel module, because it's already installed. And, in fact, I couldn't _anyway_ because you didn't have sources for 19.10. So, unless there's a workaround, I can't have anbox on a 19.10 system.

It's a Dependencies issue. that's because your OS didn't met the build requirements...

**Comment by zeankundev** [comment] 2021-12-03 05:58
Same thing here on Ubuntu 20.04
```
zeankundev@zeankundev-ThinkPad-T510:~/anbox-modules$ ./INSTALL.sh
[sudo] password for zeankundev: 

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.11.0-27-generic all KERNEL_SRC=/lib/modules/5.11.0-27-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-ashmem: 1 not found
Error! Bad return status for module build on kernel: 5.11.0-27-generic (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.11.0-27-generic all KERNEL_SRC=/lib/modules/5.11.0-27-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-binder: 1 not found
Error! Bad return status for module build on kernel: 5.11.0-27-generic (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
binder_linux          196608  0
ashmem_linux           20480  0
ls: cannot access '/dev/binder': No such file or directory
crw------- 1 root root 10, 122 Des  3 12:54 /dev/ashmem
```

**Comment by JaisonJose241** [comment] 2022-08-28 19:23
any update on this?

**Comment by sukanenen** [comment] 2022-10-29 03:16
> i am using Xubuntu 20.04, i had the same issue with Anbox until i followed koalyorg's advice
> 
> run
> 
> sudo snap install --edge --devmode anbox
> 
> then run
> 
> sudo modprobe ashmem_linux

work for me ty .. i use linux mint 21 cinnamon
